### ISSUE TITLE
Dead links to papers in README

### ISSUE THREAD

**Issue by pmla** [msg-byu/enumlib#101]
The links to the four papers in the README are useful for getting started. They are currently dead though (page says "Resource Not Found").

**Comment by wsyxbcl** [comment]
LOL, just found the same issue.

**Comment by glwhart** [comment]
Updated the links and verified that they work again. They got broken when the msg.byu.edu website was moved to a new server/platform and some folders changed.

**Comment by pmla** [comment]
Thank you @glwhart

**Comment by wsyxbcl** [comment]
> Updated the links and verified that they work again. They got broken when the msg.byu.edu website was moved to a new server/platform and some folders changed.

BTW., there are also a few dead links on your [group website](https://msg.byu.edu/publications), where full point ('.') is used instead of dash ('-'). Paper numbered 63 (Phys. Rev. B 96 014107) is an example.

**Comment by glwhart** [comment]
Thanks for noticing that. It took several hours but I finally fixed them all. Lots of things got mangled when the automatic conversion of the website was done.
