### ISSUE TITLE
error:  make convert_structures_to_enumformat.x

### ISSUE THREAD

**Issue by houzf** [msg-byu/enumlib#103]
ifort -fPIC -g -debug -error-limit 7 -heap-arrays -traceback -check bounds -warn -I../symlib/src -c ../aux_src/convert_structures_to_enumformat.f90
../aux_src/convert_structures_to_enumformat.f90(600): error #7976: An allocatable dummy argument may only be argument associated with an allocatable actual argument.   [PBAS]
  call get_HNF_of_derivative_structure(str(iStr)%title,str(iStr)%LV,str(iStr)%pos,str(iStr)%aTyp-1,CE%pLV,CE%pBas,str(iStr)%HNFlist,SNF,L,CE%eps)
-------------------------------------------------------------------------------------------------------------^
../aux_src/convert_structures_to_enumformat.f90(601): error #7976: An allocatable dummy argument may only be argument associated with an allocatable actual argument.   [PBAS]
  call get_gspace_representation(CE%pLV,CE%pBas,str(iStr)%LV,str(iStr)%pos,str(iStr)%aTyp-1,str(iStr)%HNFlist,LatDim,str(iStr)%pLabel,CE%eps)
-------------------------------------------^
../aux_src/convert_structures_to_enumformat.f90(607): error #7976: An allocatable dummy argument may only be argument associated with an allocatable actual argument.   [PBAS]

**Comment by glwhart** [comment]
Sorry to not respond for so long. I think this problem is fixed now. I don't have ifort any longer on my local machine. But it doesn't come up with gfortran. Can you try again and see if the problem still exists? If so, I'll take a look at it right away.
