### ISSUE TITLE
Error when make makestr.x

### ISSUE THREAD

**Issue by thienbinh92** [msg-byu/enumlib#113]
Hi, I tried to make makestr.x on my macbook and the terminal showed the following error. 
Hope that someone could help me out.

`/Library/Developer/CommandLineTools/usr/bin/make -C ../symlib/src
make[1]: Nothing to be done for `all'.
sed -i.bak "s/\(write(23,'(A)')\)\(.*\)/\1 \"`git describe --tags --dirty --abbrev=4`\"/" derivative_structure_generator.f90
gfortran -fPIC -g -fbounds-check -Wall -ffree-line-length-none -fno-underscoring -I../symlib/src -c derivative_structure_generator.f90
derivative_structure_generator.f90:1600:17:

     size_count = size_count + this_count*nHNF
                 1
Warning: Possible change of value in conversion from INTEGER(8) to INTEGER(4) at (1) [-Wconversion]
derivative_structure_generator.f90:1601:18:

     total_count = total_count + this_count*nHNF
                  1
Warning: Possible change of value in conversion from INTEGER(8) to INTEGER(4) at (1) [-Wconversion]
ar ru libenum.a derivative_structure_generator.o
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libenum.a(enumeration_types.o) has no symbols
ranlib  libenum.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libenum.a(enumeration_types.o) has no symbols
gfortran -fPIC -g -fbounds-check -Wall -ffree-line-length-none -fno-underscoring -I../symlib/src -c ../aux_src/makeStr.f90
../aux_src/makeStr.f90:9:19:

 use io_utils, only: co_ca
                   1
Error: Symbol ‘co_ca’ referenced at (1) not found in module ‘io_utils’
make: *** [makeStr.o] Error 1`

**Comment by shyuep** [comment]
The solution is given here: https://stackoverflow.com/questions/70450109/referenced-at-1-not-found-in-module-in-macbook-monterey 
I suggest the maintainers fix this.

**Comment by glwhart** [comment]
Fixed in the latest version (not yet tagged/released)
