### ISSUE TITLE
Compiling error and not linking to pymatgen  EnumerateStructureTransformation() 

### ISSUE THREAD

**Issue by Asif-Iqbal-Bhatti** [msg-byu/enumlib#114]
Bonjour,

I cannot compile the executable makestr.x. I have followed the steps on your Github profile but it is not compiling. Even the num_type module is not in the /src directory. 

below is the error:

ar ru libenum.a derivative_structure_generator.o
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib  libenum.a
gfortran -fPIC -g -fbounds-check -Wall -ffree-line-length-none -fno-underscoring -I../symlib/src -c makeStr.f90
makeStr.f90:9:19:

 use io_utils, only: co_ca
                   1
Error: Symbol ‘co_ca’ referenced at (1) not found in module ‘io_utils’
Makefile:131: recipe for target 'makeStr.o' failed
make: *** [makeStr.o] Error 1

I am using pymatgen how can I link this program to fortran? 
enum = EnumerateStructureTransformation()
enumerated = enum.apply_transformation(prim_cell, 100) 

Also, the purpose of the above program is to generate random structure as like in ATAT code (am I right? Is the idea the same but different approach?) where you enter the composition and based on the MC approach with the least objective function the most disordered structure is generated (Axel et al). I want to use this code to explore the chemical composition space for the ternary system.

Thank you for your help.

**Comment by glwhart** [comment]
Instead of using makestr.x, use makestr.py. It's intended to replace the
former. Eventually this will all got fixed and documented, but not until
the semester is over and I have time to work on all my github repos.

Gus Hart
Professor, Physics and Astronomy
http://msg.byu.edu

**Comment by glwhart** [comment]
`makestr.x` is fixed. Still, `makestr.py` is the more useful/flexible way to make structures from `struct_enum.out`
