### ISSUE TITLE
Can not generate derivative structures with fixed concentration range

### ISSUE THREAD

**Issue by Arindamsannyal** [msg-byu/enumlib#115]
Dear Sir

I am trying to generate structures at a fixed concentration range by using the enumlib. I am able to generate derivative structures without specifying the concentration, however, for a given concentration range, the 'enum.x' does not generate any derivative structures. The followings are my input and output files. 

Input:
----------------------------------------------------------------
unitcell
bulk
4.9927129745         0.0000000000         0.0000000000
4.1833263775         2.7252455423         0.0000000000
4.1833263775         1.2424305438         2.4255575873
4
4
0.000000000         0.000000000         0.000000000    0/1
6.679682865         1.983838043         1.212778794    2
3.200730278         0.950603587         0.581132051    3
10.158635253        3.017072440         1.844425500    3
4 4
0.1E-6
full list of labelings
#comment-concentration
1 2 2
1 2 2
2 2 2
2 2 2
----------------------------------------------------------------

Output:
----------------------------------------------------------------
 # <fortpy version="3" revision="247"></fortpy>
unitcell
bulk
  4.9927130       0.0000000       0.0000000        # a1 parent lattice vector
  4.1833264       2.7252455       0.0000000        # a2 parent lattice vector
  4.1833264       1.2424305       2.4255576        # a3 parent lattice vector
    4 # Number of points in the multilattice
  0.0000000       0.0000000       0.0000000        # d01 d-vector, labels: 0/1
  6.6796829       1.9838380       1.2127788        # d02 d-vector, labels: 2
  3.2007303      0.95060359      0.58113205        # d03 d-vector, labels: 3
  10.158635       3.0170724       1.8444255        # d04 d-vector, labels: 3
 4-nary case
   4   4 # Starting and ending cell sizes for search
 0.10000000E-06 # Epsilon (finite precision parameter)
Concentration check:
    T
Including only structures of which the concentration   of each atom is in the range:
Type 1:    1/   2 --    2/   2
Type 2:    1/   2 --    2/   2
Type 3:    2/   2 --    2/   2
Type 4:    2/   2 --    2/   2
full list of labelings (including incomplete labelings) is used
Equivalency list: 1  2  3  4
start   #tot      HNF     Hdegn   labdegn   Totdegn   #size idx    pg    SNF             HNF                 Left transform                          labeling

----------------------------------------------------------------

Can you please guide me to solve the issue. Thank you very much.

Sincerely
Arindam Sannyal

**Comment by glwhart** [comment]
It isn't possible to satisfy your concentration constraints. Sites 3 and 4
have 100% of the concentration. At most they could each have 50%, and then
sites 1 and 2 would have 0%.

Keep in mind that the denominator in the concentration inputs are totals
for the cell, not for the site.

Gus Hart
Professor, Physics and Astronomy
http://msg.byu.edu

**Comment by Arindamsannyal** [comment]
Dear Sir

Thank you very much for the explanation.

Sincerely
Arindam Sannyal
