### ISSUE TITLE
Exchangable duplicates

### ISSUE THREAD

**Issue by t-reents** [msg-byu/enumlib#120]
Dear @glwhart,

I have a question concerning the enum.x output.

I created derivative structures containing 40 atoms. Atom type 0 and 2 must have a concentration of 1/40, each. Probably I misunderstood the explanation of the `full/part` keyword but I expected to receive all derivative structures including those where 0 and 2 are exchanged. 

The output shows that this is not the case. The 35 final structures do not contain any of these exchangable duplicates. Based on the first paper, this is the behaviour which I would expect but as I mentioned before, the examples let me think that specifying `full` would also contain these structures. 

![235932245-47757843-bc4b-416b-ac89-e558d6a93857](https://user-images.githubusercontent.com/77727843/235934737-e3fcaebf-25f5-4cd4-9ddc-472eea9c928d.png)

Is there a possibility to achieve this or is this exchange something that needs to be done in a post-processing routine?

Thanks in advance!

**Comment by glwhart** [comment]
The `full` setting should generate the concentration-mirror-image structures. I'm not sure why it is not. Can you post your input file? I'll take a look...

**Comment by t-reents** [comment]
I checked the structures manually and the concentration-mirror-image structures would be duplicates (due to the positions etc.). Therefore, there is no problem. I'll close this issue and sorry for the confusion.
