### ISSUE TITLE
How to match elements to a created structure

### ISSUE THREAD

**Issue by yanwenliao** [msg-byu/enumlib#121]
Below is a POSCAR file of a structure that I exported through "python makeStr.py"
Nb str #: 1
1.000
  0.000000000  6.641040000  0.000000000
  0.000000000  0.000000000  6.641040000
  6.641040000  0.000000000  0.000000000
  2   14   
Direct
  0.000000000   0.000000000   0.000000000
  0.000000000   0.500000000   0.000000000
  0.500000000   0.000000000   0.000000000
  0.500000000   0.500000000   0.000000000
  0.000000000   0.000000000   0.500000000
  0.000000000   0.500000000   0.500000000
  0.500000000   0.000000000   0.500000000
  0.500000000   0.500000000   0.500000000
  0.250000000   0.250000000   0.250000000
  0.250000000   0.750000000   0.250000000
  0.750000000   0.250000000   0.250000000
  0.750000000   0.750000000   0.250000000
  0.250000000   0.250000000   0.750000000
  0.250000000   0.750000000   0.750000000
  0.750000000   0.250000000   0.750000000
  0.750000000   0.750000000   0.750000000

But how do I export with attaching the elements Nb and U as shown in line 6
Nb str #: 1
1.000
  0.000000000  6.641040000  0.000000000
  0.000000000  0.000000000  6.641040000
  6.641040000  0.000000000  0.000000000
Nb U
2   14   
Direct
  0.000000000   0.000000000   0.000000000
  0.000000000   0.500000000   0.000000000
  0.500000000   0.000000000   0.000000000
  0.500000000   0.500000000   0.000000000
  0.000000000   0.000000000   0.500000000
  0.000000000   0.500000000   0.500000000
  0.500000000   0.000000000   0.500000000
  0.500000000   0.500000000   0.500000000
  0.250000000   0.250000000   0.250000000
  0.250000000   0.750000000   0.250000000
  0.750000000   0.250000000   0.250000000
  0.750000000   0.750000000   0.250000000
  0.250000000   0.250000000   0.750000000
  0.250000000   0.750000000   0.750000000
  0.750000000   0.250000000   0.750000000
  0.750000000   0.750000000   0.750000000

I tried add "-elements Nb U" after "python makeStr.py " like " python makeStr.py -elements Nb U 1 -flags ",but it didn't work.
![1710852959303](https://github.com/msg-byu/enumlib/assets/154332792/8431949f-39a8-48fb-9f7d-14c2dde78d5b)

**Comment by YangZihangYNU** [comment]
I have the same problem............

**Comment by yanwenliao** [comment]
I wrote it directly in the bash script：

infile=struct_enum.in.ex5
outfile=struct_enum.out
#运行  
    ../../src/enum.x $infile
#提取struct_enum.out文件的结构类型总数
last_line=$(tail -n 1 $outfile)
total=$(echo $last_line | awk '{print $1}' | tr -d ' ')
#生成poscar
python makeStr.py 1 $total -flags
#更改poscar细节并且移动到poscar文件夹
 for ((j=1; j<=$total; j++)); do
 filename="vasp.$j"
 sed -i '6i Nb U' "$filename" 
 mv "$filename" poscar/"$j.vasp"
 done

**Comment by yanwenliao** [comment]
I wrote it directly in the bash script：

infile=struct_enum.in.ex5
outfile=struct_enum.out
#运行
../../src/enum.x $infile
#提取struct_enum.out文件的结构类型总数
last_line=$(tail -n 1 $outfile)
total=$(echo $last_line | awk '{print $1}' | tr -d ' ')
#生成poscar
python makeStr.py 1 $total -flags
#更改poscar细节并且移动到poscar文件夹
for ((j=1; j<=$total; j++)); do
filename="vasp.$j"
sed -i '6i Nb U' "$filename"
mv "$filename" poscar/"$j.vasp"
done




此外，为了实现连续置换，我是在16个原子里置换别的原子，从1置换到16，下面是脚本的完整内容：




#!/bin/bash

mkdir&nbsp; poscar

atoms=16

infile=struct_enum.in.ex5

outfile=struct_enum.out




for ((i=1; i<=$atoms; i++)); do

#更改输入文件倒数一二行

&nbsp; &nbsp; sed -i "$(($(wc -l < $infile) - 1))s/.*/$i $i $atoms/" $infile

&nbsp; &nbsp; sed -i "$(($(wc -l < $infile)))s/.*/$(($atoms-$i)) $(($atoms-$i)) $atoms/" $infile

#运行&nbsp;&nbsp;

&nbsp; &nbsp; ../../src/enum.x $infile

#提取struct_enum.out文件的结构类型总数

last_line=$(tail -n 1 $outfile)

total=$(echo $last_line | awk '{print $1}' | tr -d ' ')

#生成poscar

python makeStr.py 1 $total -flags

#更改poscar细节并且移动到poscar文件夹

&nbsp;for ((j=1; j<=$total; j++)); do

&nbsp;filename="vasp.$j"

&nbsp;sed -i '6i Nb U' "$filename"&nbsp;

&nbsp;mv "$filename" poscar/"$i-$j.vasp"

&nbsp;done

#

done




在命令行直接输入： “bash 脚本名” 就可以了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "msg-byu/enumlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月26日(星期二) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [msg-byu/enumlib] How to match elements to a created structure (Issue #121)





 
I have the same problem............
