### ISSUE TITLE
Fortpy can't find timing.o file in uncle/src/

### ISSUE THREAD

**Issue by wsmorgan** [msg-byu/enumlib#2]
I think this is because it's not an .f90 file but a .c  and .h files. Any thoughts on a workaround?

**Comment by rosenbrockc** [comment]
See the `<libraries>` tag in the global configuration XML file (https://github.com/rosenbrockc/fortpy/blob/master/fortpy/config.xml). Just keep a single compiled version of `timing.o` somewhere and reference it with an `<include>` tag.

**Comment by wsmorgan** [comment]
Okay, I've got something working for now.
