### ISSUE TITLE
Mac OSX compile fails

### ISSUE THREAD

**Issue by shyuep** [msg-byu/enumlib#29]
The master branch currently fails with the following error during compile on Mac OSX:

```
bash -c "echo `svnversion` > version.enum"
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/bin/bash
  Reason: image not found
make: *** [sorting.o] Abort trap: 6
```

Commenting out line 128 in the Makefile solves this problem without side effects. I am not quite sure what this line does, but I recommend either modifying the line to work or to remove it.

**Comment by glwhart** [comment]
This line used to store the current svn version number of the code. As we no longer use svn, it's out of date. I'll delete it. Thanks.
