### ISSUE TITLE
polya seems to have disappeared?

### ISSUE THREAD

**Issue by shyuep** [msg-byu/enumlib#40]
Polya dependency seems to have disappeared from the repo.

**Comment by wsmorgan** [comment]
The polya submodule dependency has been absorbed into symlib so we are removing it as a dependency here.

**Comment by shyuep** [comment]
Well, the current repo does not work. When I try to make enum.x, I get 

```
 use classes, only: polya

Fatal Error: Can't open module file ‘classes.mod’ for reading at (1): No such file or directory
compilation terminated.
```

**Comment by wsmorgan** [comment]
We had noticed this issue and the pending pull request should fix it once it is merged in. In the meantime you can pull from my fork of the repo if you are in need of the fix, https://github.com/wsmorgan/enumlib

**Comment by mkhorton** [comment]
For anyone else looking for this, polya can also be found at https://github.com/rosenbrockc/polya (this seems like it was the version previously included in enumlib)

**Comment by glwhart** [comment]
Hi Matthew,

Sorry to pull the carpet out from under you.  https://github.com/rosenbrockc/polya was always the place for polya. Enumlib will pull `polya`* and `symlib` automatically now if you git clone with the recursive flag.
`git clone --recursive https://github.com/msg-byu/enumlib.git`

We were trying to make things simpler for enumlib users...

*`polya` has become part of `symlib`

**Comment by mkhorton** [comment]
Hi Gus,

I know that's how it used to be, but `git clone --recursive` seems to be missing `polya` at the moment? At least the current version on GitHub is missing the reference. I don't see it in the `symlib` repo either.

**Comment by mkhorton** [comment]
Ah, I see the `polya` commit in symlib (classes.f90 and intertolls.f90) ... perhaps the README just needs to be updated in enumlib? I was looking for a polya folder.

**Comment by glwhart** [comment]
You're right. Good catch. Thanks. I've updated the README.
