### ISSUE TITLE
Help with fixed concentrations input

### ISSUE THREAD

**Issue by afonari** [msg-byu/enumlib#50]
Hi, I'm trying to set-up a fixed concentration run:
```1011104
bulk
5.64413 0.00000 0.00000
2.82206 4.88796 0.00000
-0.00000 -0.00000 13.82523
2
24
0.00000 0.00000 0.00000 0/1
1.41103 0.81466 2.30421 0/1
4.23309 0.81466 2.30421 0/1
2.82206 3.25864 2.30421 0/1
5.64413 3.25864 2.30421 0/1
7.05516 4.07330 4.60841 0/1
4.23309 4.07330 4.60841 0/1
5.64413 1.62932 4.60841 0/1
2.82206 1.62932 4.60841 0/1
4.23309 2.44398 0.00000 0/1
1.41103 2.44398 0.00000 0/1
2.82206 -0.00000 0.00000 0/1
-0.00000 -0.00000 6.91261 0/1
1.41103 0.81466 9.21682 0/1
4.23309 0.81466 9.21682 0/1
2.82206 3.25864 9.21682 0/1
5.64413 3.25864 9.21682 0/1
7.05516 4.07330 11.52102 0/1
4.23309 4.07330 11.52102 0/1
5.64413 1.62932 11.52102 0/1
2.82206 1.62932 11.52102 0/1
4.23309 2.44398 6.91261 0/1
1.41103 2.44398 6.91261 0/1
2.82206 -0.00000 6.91261 0/1
1 1
0.001
full
23 23 24
1 1 24
```

this results only in one structure in the output with labeling:
```
100000000000000000000000
```

I was expecting 24 structures (maybe with symmetry-equivalents removed):
```
100000000000000000000000
010000000000000000000000
001000000000000000000000
...
```

Can you please help me understand the result?

Thanks.

**Comment by glwhart** [comment]
If all of these sites are equivalent, then there will only be one structure
that is unique. Do all the sites have the same wyckoff label?

Gus Hart
http://msg.byu.edu
Assoc. Dean, CPMS
http://cpms.byu.edu

**Comment by afonari** [comment]
> Do all the sites have the same wyckoff label?

Yes. But for P1 symmetry, any position in the cell has the same wyckoff label (=a): http://www.cryst.ehu.es/cgi-bin/cryst/programs/nph-wp-list?gnum=1

**Comment by glwhart** [comment]
Then all the 32 cells you expected are symmetrically-equivalent. It's
merely a choice of origin.

Gus Hart
http://msg.byu.edu
Assoc. Dean, CPMS
http://cpms.byu.edu

**Comment by afonari** [comment]
Thanks for explanation.
