### ISSUE TITLE
Possible bug in makeStr.py

### ISSUE THREAD

**Issue by feifzhou** [msg-byu/enumlib#54]
I encountered a problem with makeStr.py when k=4:

[zhou6@quartz2498 coupled-lattice]$./makeStr.py 1
Traceback (most recent call last):
  File "./makeStr.py", line 949, in <module>
    run(_parser_options())
  File "./makeStr.py", line 946, in run
    _make_structures(args)
  File "./makeStr.py", line 822, in _make_structures
    (system, structure_data) = _read_enum_out(args)
  File "./makeStr.py", line 697, in _read_enum_out
    this_struct["strN"] = int(data[0])
ValueError: invalid literal for int() with base 10: 'Concentration'

The enum.x output is

 # <fortpy version="3" revision="247"></fortpy>
Ba1 Si4 N4
bulk
 -4.1280604       4.1280604       1.7254000        # a1 parent lattice vector
  4.1280604      -4.1280604       1.7254000        # a2 parent lattice vector
  4.1280604       4.1280604      -1.7254000        # a3 parent lattice vector
    5 # Number of points in the multilattice
  2.6171903       1.0980641       1.7254000        # d01 d-vector, labels: 0/1
 -1.0980641       2.6171903       1.7254000        # d02 d-vector, labels: 0/1
  1.5108701       3.0299963       0.0000000        # d03 d-vector, labels: 0/1
  5.2261244       1.5108701       0.0000000        # d04 d-vector, labels: 0/1
  0.0000000       0.0000000       0.0000000        # d05 d-vector, labels: 2/3
 4-nary case
   1   3 # Starting and ending cell sizes for search
 0.10000000E-05 # Epsilon (finite precision parameter)
Concentration check:
    T
Including only structures of which the concentration   of each atom is in the range:
Type 1:   20/ 100 --   20/ 100
Type 2:    0/ 100 --  100/ 100
Type 3:    1/ 100 --   99/ 100
Type 4:    1/ 100 --   99/ 100
full list of labelings (including incomplete labelings) is used
...

The reason seems to be that when k=4 the line

            if line_count == 11 + system["nD"]:
                if "T" == temp.strip().split()[0]:
                    adjust = system["nD"] + system["k"] + 1
                else:
                    adjust = system["nD"]

was not readily processed when line 15 "Concentration check" was, resulting in adjust=0 (initial value) and crash.

I had a simple patch for makeStr.py:

668,669c668,670
<     system["nD"] = 0
<     adjust = 0
---
>     import linecache
>     system["nD"] = int(linecache.getline(args["input"],7).split()[0])
>     adjust = system["nD"]

**Comment by wsmorgan** [comment]
@feifzhou How were you calling `makeStr.py`? What, if any, command line arguments were you using? I just want to make sure I can reproduce the bug.

**Comment by wsmorgan** [comment]
@feifzhou Never mind I managed to reproduce the bug. I'll be pushing a permanent fix up shortly.
