### ISSUE TITLE
What to do with co_ca in io_utils.f90

### ISSUE THREAD

**Issue by wsmorgan** [msg-byu/enumlib#6]
I just moved on to io_utils and have no idea what to do with the co_ca subroutine for a unit test. My main difficulty is that it has no output for fortpy to test. Any ideas?

**Comment by rosenbrockc** [comment]
I would just add a `<skip reason="Indirectly tested by the other input
reading routines." />` above it and not worry about it. If the other
routines work, then it must also work.

**Comment by wsmorgan** [comment]
I was thinking similarly, if anything in co_ca doesn't work then the whole io_utils module will fail too.
