### ISSUE TITLE
error when using enumlib

### ISSUE THREAD

**Issue by Backtorp** [msg-byu/enumlib#68]
Dear users,
I am writing to you as I got into trouble when using enum.x

I am trying to follow the procedure in:
https://github.com/materialsvirtuallab/matgenb/blob/master/notebooks/2016-09-08-Data-driven%20First%20Principles%20Methods%20for%20the%20Study%20and%20Design%20of%20Alkali%20Superionic%20Conductors%20Part%201%20-%20Structure%20Generation.ipynb

I am using another cif-file than they are using, but I guess that should not be the problem.
however, I end up with the error i the attached file.
Can you help me with this?

Kind regards,
Carina

![errormessage](https://user-images.githubusercontent.com/38094847/38350218-a8a97c00-38aa-11e8-9bb4-ab836cede900.png)

**Comment by glwhart** [comment]
I'm not sure how to help you. The problem seems to be with the python script, not with `enum` itself. Maybe you could post your question on the github page for the python code...

**Comment by Backtorp** [comment]
Dear Gus,

 

Thank you for trying to help. I think that my problem is due to that it is run on windows.

When my colleague tried the same procedure at his linux computer it worked fine.

 

Kind regards,

Carina

 

Från: Gus Hart <notifications@github.com> 
Skickat: den 7 april 2018 01:13
Till: msg-byu/enumlib <enumlib@noreply.github.com>
Kopia: Backtorp <carina.backtorp@wendelsbergskemi.se>; Author <author@noreply.github.com>
Ämne: Re: [msg-byu/enumlib] error when using enumlib (#68)

 

I'm not sure how to help you. The problem seems to be with the python script, not with enum itself. Maybe you could post your question on the github page for the python code...
