### ISSUE TITLE
fatal error when compile enumlib

### ISSUE THREAD

**Issue by woshijamess** [msg-byu/enumlib#71]
I encountered fatal error when compile symlib.

The erroe message is:

login-2:src$ make F90=gfortran
gfortran -g -fbounds-check -fPIC -pedantic -Wall -ffree-line-length-none -c itertools.f90
itertools.f90:105.59:

    class(vararray), allocatable, intent(in) :: elements(:)
                                                           1
Fatal Error: Polymorphic array at (1) not yet supported
make: *** [itertools.o] Error 1

**Comment by wsmorgan** [comment]
What version of gfortran are you using?

**Comment by woshijamess** [comment]
My verison is GNU Fortran (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

**Comment by afonari** [comment]
Might be related: https://gcc.gnu.org/ml/fortran/2011-08/msg00258.html

**Comment by glwhart** [comment]
@woshijamess Did you ever get this sorted out? Did you try a different compiler?

**Comment by glwhart** [comment]
Closing this issue until we can show that the crash is still happening and not a problem with the compiler.
