### ISSUE TITLE
Arrow enumeration fails for non cubic cases

### ISSUE THREAD

**Issue by wsmorgan** [msg-byu/enumlib#72]
When we built the arrow enumeration we assumed that the arrows would only point in the 6 cardinal directions. This doesn't work for anything that is not cubic because the symmetry group doesn't map the arrows to each other.

**Comment by glwhart** [comment]
Given the fact that we have no intention of fixing this (it's less of a bug and more of a design flaw), especially given the apparent lack of interest. I'm going to close this.
