### ISSUE TITLE
Failure when enumerate A1.2B0.8C1.4D0.6

### ISSUE THREAD

**Issue by zhongpc** [msg-byu/enumlib#77]
When using pymatgen EnumlibAdaptor to enumerate A1.2B0.8C1.4D0.6 with {A: 6/10, B: 4/10} and {C: 7/10, D: 3/10}. It results an error: 

At line 815 of file labeling_related.f90
Fortran runtime error: Index '1' of dimension 1 of array 'vslabels' outside of expected range (1:0)

But it runs well for composition  A_1.2B_0.8C_1.2D_0.4 with {A: 6/10, B: 4/10} and {C: 8/10, D: 2/10}.
and  A_1.2B_0.8C_1.8D_0.2 with {A: 6/10, B: 4/10} and {C: 9/10, D: 1/10}. I can get the right composition but cannot increase D to 3/10.

Thanks

**Comment by zhongpc** [comment]
At line 815 of file labeling_related.f90
Fortran runtime error: Index '1' of dimension 1 of array 'vslabels' outside of expected range (1:0)

Error termination. Backtrace:
#0  0x10b72557c
#1  0x10b726285
#2  0x10b72662a
#3  0x10b5fa763
#4  0x10b5fe0ce
#5  0x10b616379
#6  0x10b688cf1
#7  0x10b688d2e

**Comment by glwhart** [comment]
@zhongpc Could you send your `struct_enum.in` file for this?

**Comment by glwhart** [comment]
Or tell us the input that `pymatgen` uses? So that we can try and debug?

**Comment by glwhart** [comment]
@zhongpc If you can give us input so that we can test, we will reopen this. Until then, I'm going to close the issue.
