### ISSUE TITLE
New behavior is different that the old one

### ISSUE THREAD

**Issue by afonari** [msg-byu/enumlib#81]
This seems to be related to #79.

With the code before the change, I'm getting one structure output for the attached input:
```
---------------------------------------------------------------------------------------------
Calculating derivative structures for index n= 1 to  1
Including only structures of which the concentration of each atom is in the range:
Type: 1: 237/240--237/240
Type: 2: 1/240--1/240
Type: 3: 2/240--2/240
Volume       CPU        #HNFs  #SNFs    #reduced    % dups      volTot      RunTot
   1         0.7048        1     1         1        0.0000           2           2
---------------------------------------------------------------------------------------------
```

For the new code, I'm getting zero:
```
---------------------------------------------------------------------------------------------
Calculating derivative structures for index n= 1 to  1
Including only structures of which the concentration of each atom is in the range:
Type: 1: 237/240--237/240
Type: 2: 1/240--1/240
Type: 3: 2/240--2/240
Volume       CPU        #HNFs  #SNFs    #reduced    % dups      volTot      RunTot
---------------------------------------------------------------------------------------------
```

Example file: [enumerate_periodic.in.txt](https://github.com/msg-byu/enumlib/files/2803457/enumerate_periodic.in.txt)

**Comment by glwhart** [comment]
@afonari Thanks for the feedback. I'm guessing that it's a problem with the concentration specification. It might only be "active" sites that are included in the concentration now. If so, we'll have to change the way the input is specified or adjust the internal checks. I'll see what I can do.

As a user, what would be more convenient, specifying the concentrations of only the "active sites"? or specifying total concentrations (like you've done here)? With lots of inactive sites, it seem the former would be more convenient, but I'd like to hear your opinion.

**Comment by afonari** [comment]
Sorry for the late reply. In my view, explicit is better than implicit, so I suggest keeping both active and inactive sites (old format).

**Comment by glwhart** [comment]
In my personal fork, I have a new version that is working again. I'm going to set up some unit tests. Once those are done, I'll push the new version.

**Comment by afonari** [comment]
Sounds great! Will test it once it's merged.

**Comment by afonari** [comment]
Any updates on this?

**Comment by glwhart** [comment]
The code has been updated but I have not pushed the changes yet.

An enhancement in the SNF routine in symlib changes the enumlib output in
some cases, breaking some of the unit tests for enumlib. I believe that the
new output is *equivalent* (but not identical) to the old output. However,
proving this definitively has been taking a lot of time. I had to write a
code to find the automorphism between the two representations. It's not
quite done yet. I could push the changes to my personal fork and have you
pull from there if you need something sooner. I *believe* the code is
correct; I just can't pass the unit tests yet.

I hope to have everything pushed by the end of next week. Fingers crossed.


Gus Hart
http://msg.byu.edu
Assoc. Dean, CPMS
http://cpms.byu.edu

**Comment by afonari** [comment]
> I could push the changes to my personal fork and have you pull from there if you need something sooner.

This sounds great. I can definitely start testing sooner.

**Comment by glwhart** [comment]
I've got a few tight deadlines. It'll probably be two weeks before I can
check and push the changes to my personal branch. Sorry about that.

Gus Hart
http://msg.byu.edu
Assoc. Dean, CPMS
http://cpms.byu.edu

**Comment by afonari** [comment]
Np, whenever you are ready sounds good to me.

**Comment by afonari** [comment]
Any updates on this?

**Comment by glwhart** [comment]
All the fallout that happened as a result of the SNF routine change has been dealt with. It was super tricky to get all the math right so that the "compare" code worked correctly. Not all the unit tests have been brought back online yet, but as soon as today's PR is accepted, I think the code will be fixed.
