### ISSUE TITLE
Possible regression, "d-vector didn't permute in map_dvector_permutation"

### ISSUE THREAD

**Issue by mkhorton** [msg-byu/enumlib#83]
This input file worked with a previous version of enumlib but now fails with the error below.

Has the input file format changed, or is it otherwise mal-formed, or is this a bug in the current enumlib?

Many thanks for any help you can provide.

Output file:

```
---------------------------------------------------------------------------------------------
Calculating derivative structures for index n= 1 to  2
Including only structures of which the concentration of each atom is in the range:
Type: 1: 10/20--10/20
Type: 2: 10/20--10/20
Volume       CPU        #HNFs  #SNFs    #reduced    % dups      volTot      RunTot
Original d-set member was not inside the unit cell. It has been remapped.
Original:  4.528   2.614   3.453
Remapped:  0.000  -0.000  -0.000
 d-vector didn't permute in map_dvector_permutation
 This usually means that the d-set from the input structure and the d-set
 from the struct_enum.out have a different origin or don't live in the same
 unit cell. This probably isn't your fault---the code should overcome this.
 2  0
```

Input file:

```
Mmb2 Mma2 Ca6 Co4 O12
bulk
-4.528350 2.614444 3.452967
0.000000 -5.228888 3.452967
4.528350 2.614444 3.452967
2
2
4.528350 2.614444 3.452967 0/1
-0.000000 0.000000 5.179450 0/1
1 2
0.001
partial
10 10 20
10 10 20
```

**Comment by mkhorton** [comment]
This also fails if we change the setting:

```
Mmb2 Mma2 Ca6 Co4 O12
bulk
4.528350 -2.614444 3.452967
0.000000 5.228888 3.452967
-4.528350 -2.614444 3.452967
2
2
0.000000 0.000000 5.179450 0/1
0.000000 0.000000 0.000000 0/1
1 2
0.001
partial
10 10 20
10 10 20
```

gives:

```
---------------------------------------------------------------------------------------------
Calculating derivative structures for index n= 1 to  2
Including only structures of which the concentration of each atom is in the range:
Type: 1: 10/20--10/20
Type: 2: 10/20--10/20
Volume       CPU        #HNFs  #SNFs    #reduced    % dups      volTot      RunTot
 d-vector didn't permute in map_dvector_permutation
 This usually means that the d-set from the input structure and the d-set
 from the struct_enum.out have a different origin or don't live in the same
 unit cell. This probably isn't your fault---the code should overcome this.
 1  0
```

**Comment by glwhart** [comment]
At the last update, "concentration-restricted" cases were unexpectedly
broken. A fix for this has been developed but it's taken some time to prove
that all of the unit tests still pass. In the next few weeks, everything
should be working again (and some cases will run much, much faster than
they did originally)

Gus Hart
Professor, Physics and Astronomy
http://msg.byu.edu
Dean, Physical and Mathematical Sciences
http://cpms.byu.edu

**Comment by mkhorton** [comment]
Fantastic, we will look forward to it! Thank you for the quick response.

**Comment by shyuep** [comment]
@glwhart Thanks Gus. As an aside, may I suggest that enumlib provide some versioning and tagged releases? I see there was one in Aug 2017 (v1.0.8). That way, we can peg dependent software on a specific version and identify issues across versions more easily.

**Comment by glwhart** [comment]
Maybe, you mean something different, but every PR that is accepted is
accompanied by a change in the version number, following the standard
practice for open source software. See HISTORY.md. Is that different from
what you mean?

**Comment by mkhorton** [comment]
I believe @shyuep is referring specifically to the releases on this page: https://github.com/msg-byu/enumlib/releases

The motivation here is that there may be several commits or PRs between any given release, so you can nominate a specific commit to be a "release" commit and tag it as such, then the releases page on GitHub gives someone new to the repository an easy place to look to download historical archives of the code for any given versioned release. It's really a convenience more than anything.

**Comment by glwhart** [comment]
I see. Yeah, I forgot that that even existed. I would have intended to release 2.0 that way. But since it unexpectedly broke some cases, I'll wait until I've pushed my changes to fix all that before I do an official release. The changes have been made but it's been devilishly difficult to make sure all the unit tests pass. Changes were made to the SNF routine in `symlib` to make our kpoint folding code more numerically stable. As a result, enumlib output changed...but was still equivalent (isomorphic) to the old (but not identical). It took a long time to come up with a mapping algorithm to *prove* that the old results and new results were equivalent. I had to remember all the group theory (and then some) that went into the original algorithm. Hope to have everything updated in a few weeks.

**Comment by mkhorton** [comment]
Hi Gus, I was just wondering if there was any update on this bug fix? Thank you for the added context above.

**Comment by glwhart** [comment]
I've been working on this. I think it's close. Getting a new job slowed me
down a lot. I hope that a new release will be made by Aug 15.

**Comment by mkhorton** [comment]
Thanks for the update! Congratulations on the new job, will look forward to the new release (we have a summer student who's quite keen to make use of some enumlib-related functionality, but we can use the older version of enumlib just fine for now so we'll stick to that for the time being).

**Comment by mkhorton** [comment]
Hello, I saw there were some commits suggesting this bug might have been fixed, but unfortunately the above input still gives an error for the latest version from master (compiled with gfortran 9.1.0). Please ignore this message if this is already known to you!

Edit: it also still fails when compiled via ifort 19.

**Comment by glwhart** [comment]
Would you try version 2.0.3 and see how it goes?

As for ifort, I don't have that on my laptop anymore. (I could go to the supercomputer but...). Can you tell me what the problem is with compiling? gfortran is usually pickier than ifort, so it's surprising that ifort is not working...

**Comment by mkhorton** [comment]
Sorry, to clarify enumlib compiles fine with both gfortran and ifort, it’s
that the bug mentioned above is still present in the new version. I tried
the ifort version yesterday with the latest version from master.

**Comment by mkhorton** [comment]
I can confirm the latest version seems to work :-) Thank you for fixing! I think I must have compiled before the 2.0.3 changes were merged in yesterday.

**Comment by glwhart** [comment]
Thanks. I’ll close then. Let me know of any other cases you find that fail
